spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  # for test
  h2:
    console:
      enabled: true
  datasource:
    # for test
    url: jdbc:h2:~/team-by-team-test;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # for test
    show-sql: true # for test

jwt:
  access:
    secret: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    expiration: 1800000 # 30분

  refresh:
    secret: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    expiration: 86400000 # 1일

sse:
  cache-schedule-period: 60 * 1000

aws:
  s3:
    region: abcd
    bucket: abcd
    asset-root-directory: asset/root/directory
    image-directory: /a/b
    ical-directory: /i/c
  cloud-front:
    region: aws-global
    domain: abcd
    asset-distribution-id: asdf


oauth:
  google:
    client-id: client-id
    client-secret: client-secret
    end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes: scope1, scope2
    access-type: access-type
    token-uri: https://oauth2.googleapis.com/token
    redirect-uri: redirect-uri

base-domain:
  front: "https://localhost:8080"
