name: backend deploy dev api docs

on:
  pull_request:
    types:
      - closed
    branches: [ "develop" ]
    paths:
      - 'backend/src/docs/**'

permissions:
  contents: read

jobs:
  build-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend
    
    steps:

    - name: Set up Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Give permission for Gradle
      run: chmod +x gradlew
      
    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload docs html file artifact
      uses: actions/upload-artifact@v3
      with:
        name: DocsHtml
        path: backend/src/main/resources/docs/index.html
        
  deploy:
    needs: build-and-upload
    runs-on: self-hosted
    steps:
      - name: Download docs html file from artifact
        uses: actions/download-artifact@v3
        with:
          name: DocsHtml
          path: backend/dev/docs/
        
      - name: Move docs file to deploy
        working-directory: backend/dev/
        run: |
          mv docs/index.html /home/ubuntu/team-by-team/docs/
      
